x-airflow-common: &airflow-common
  image: apache/airflow:2.7.1
  environment: &airflow-common-env
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./scripts:/opt/airflow/scripts
    - ./requirements.txt:/opt/airflow/requirements.txt
    - ./entrypoint.sh:/entrypoint.sh

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      timeout: 5s
    ports:
      - "5433:5432"

  airflow-webserver:
    <<: *airflow-common
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    command: ["webserver"]
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    <<: *airflow-common
    depends_on:
      - airflow-webserver
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    command: ["scheduler"]
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://airflow-webserver:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres-data: